version: '3.4'

services:
  weatherappstarter:
    image: weatherappstarter
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
